make: ILS.c ILS.h Visual.c Map_drawing.c ATT_ind_drawing.c ILS_ind_drawing.c Markers_ind_drawing.c Runway_drawing.c Control_pannel_drawing.c Borders_drawing.c
	gcc -o ILS Visual.c Map_drawing.c ATT_ind_drawing.c ILS_ind_drawing.c Markers_ind_drawing.c Runway_drawing.c Control_pannel_drawing.c Borders_drawing.c ILS.c -lm -lpthread `pkg-config --cflags --libs gtk+-3.0`
